/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CLAVES_H_RPCGEN
#define _CLAVES_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct Coord {
	int x;
	int y;
};
typedef struct Coord Coord;

struct set_args {
	int key;
	char *value1;
	int N_value2;
	struct {
		u_int V_value2_len;
		double *V_value2_val;
	} V_value2;
	Coord value3;
};
typedef struct set_args set_args;

struct get_args {
	int key;
};
typedef struct get_args get_args;

struct delete_args {
	int key;
};
typedef struct delete_args delete_args;

struct exist_args {
	int key;
};
typedef struct exist_args exist_args;

#define CLAVES_PROG 0x31234567
#define CLAVES_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define rpc_set_value 1
extern  int * rpc_set_value_1(set_args *, CLIENT *);
extern  int * rpc_set_value_1_svc(set_args *, struct svc_req *);
#define rpc_get_value 2
extern  set_args * rpc_get_value_1(get_args *, CLIENT *);
extern  set_args * rpc_get_value_1_svc(get_args *, struct svc_req *);
#define rpc_delete_key 3
extern  int * rpc_delete_key_1(delete_args *, CLIENT *);
extern  int * rpc_delete_key_1_svc(delete_args *, struct svc_req *);
#define rpc_modify_value 4
extern  int * rpc_modify_value_1(set_args *, CLIENT *);
extern  int * rpc_modify_value_1_svc(set_args *, struct svc_req *);
#define rpc_exist 5
extern  int * rpc_exist_1(exist_args *, CLIENT *);
extern  int * rpc_exist_1_svc(exist_args *, struct svc_req *);
#define rpc_destroy 6
extern  int * rpc_destroy_1(void *, CLIENT *);
extern  int * rpc_destroy_1_svc(void *, struct svc_req *);
extern int claves_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define rpc_set_value 1
extern  int * rpc_set_value_1();
extern  int * rpc_set_value_1_svc();
#define rpc_get_value 2
extern  set_args * rpc_get_value_1();
extern  set_args * rpc_get_value_1_svc();
#define rpc_delete_key 3
extern  int * rpc_delete_key_1();
extern  int * rpc_delete_key_1_svc();
#define rpc_modify_value 4
extern  int * rpc_modify_value_1();
extern  int * rpc_modify_value_1_svc();
#define rpc_exist 5
extern  int * rpc_exist_1();
extern  int * rpc_exist_1_svc();
#define rpc_destroy 6
extern  int * rpc_destroy_1();
extern  int * rpc_destroy_1_svc();
extern int claves_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Coord (XDR *, Coord*);
extern  bool_t xdr_set_args (XDR *, set_args*);
extern  bool_t xdr_get_args (XDR *, get_args*);
extern  bool_t xdr_delete_args (XDR *, delete_args*);
extern  bool_t xdr_exist_args (XDR *, exist_args*);

#else /* K&R C */
extern bool_t xdr_Coord ();
extern bool_t xdr_set_args ();
extern bool_t xdr_get_args ();
extern bool_t xdr_delete_args ();
extern bool_t xdr_exist_args ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CLAVES_H_RPCGEN */
