/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPC_H_RPCGEN
#define _RPC_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif

#define MAX_STR 256
#define MAX_V2 32

struct coord {
	int x;
	int y;
};
typedef struct coord coord;

struct tupla {
	int key;
	char *value1;
	int N_value2;
	struct {
		u_int V_value2_len;
		double *V_value2_val;
	} V_value2;
	coord value3;
};
typedef struct tupla tupla;

struct get_resp {
	int status;
	tupla data;
};
typedef struct get_resp get_resp;

#define CLAVES_PROG 0x31234567
#define CLAVES_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define SET_VALUE 1
extern  enum clnt_stat set_value_1(tupla *, int *, CLIENT *);
extern  bool_t set_value_1_svc(tupla *, int *, struct svc_req *);
#define MODIFY_VALUE 2
extern  enum clnt_stat modify_value_1(tupla *, int *, CLIENT *);
extern  bool_t modify_value_1_svc(tupla *, int *, struct svc_req *);
#define DELETE_KEY 3
extern  enum clnt_stat delete_key_1(int *, int *, CLIENT *);
extern  bool_t delete_key_1_svc(int *, int *, struct svc_req *);
#define EXIST 4
extern  enum clnt_stat exist_1(int *, int *, CLIENT *);
extern  bool_t exist_1_svc(int *, int *, struct svc_req *);
#define GET_VALUE 5
extern  enum clnt_stat get_value_1(int *, get_resp *, CLIENT *);
extern  bool_t get_value_1_svc(int *, get_resp *, struct svc_req *);
#define DESTROY 6
extern  enum clnt_stat destroy_1(void *, int *, CLIENT *);
extern  bool_t destroy_1_svc(void *, int *, struct svc_req *);
extern int claves_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SET_VALUE 1
extern  enum clnt_stat set_value_1();
extern  bool_t set_value_1_svc();
#define MODIFY_VALUE 2
extern  enum clnt_stat modify_value_1();
extern  bool_t modify_value_1_svc();
#define DELETE_KEY 3
extern  enum clnt_stat delete_key_1();
extern  bool_t delete_key_1_svc();
#define EXIST 4
extern  enum clnt_stat exist_1();
extern  bool_t exist_1_svc();
#define GET_VALUE 5
extern  enum clnt_stat get_value_1();
extern  bool_t get_value_1_svc();
#define DESTROY 6
extern  enum clnt_stat destroy_1();
extern  bool_t destroy_1_svc();
extern int claves_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_coord (XDR *, coord*);
extern  bool_t xdr_tupla (XDR *, tupla*);
extern  bool_t xdr_get_resp (XDR *, get_resp*);

#else /* K&R C */
extern bool_t xdr_coord ();
extern bool_t xdr_tupla ();
extern bool_t xdr_get_resp ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPC_H_RPCGEN */
