/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "rpc.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
set_value_1(tupla *argp, int *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, SET_VALUE,
		(xdrproc_t) xdr_tupla, (caddr_t) argp,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
modify_value_1(tupla *argp, int *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, MODIFY_VALUE,
		(xdrproc_t) xdr_tupla, (caddr_t) argp,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
delete_key_1(int *argp, int *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, DELETE_KEY,
		(xdrproc_t) xdr_int, (caddr_t) argp,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
exist_1(int *argp, int *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, EXIST,
		(xdrproc_t) xdr_int, (caddr_t) argp,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
get_value_1(int *argp, get_resp *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, GET_VALUE,
		(xdrproc_t) xdr_int, (caddr_t) argp,
		(xdrproc_t) xdr_get_resp, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
destroy_1(void *argp, int *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, DESTROY,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}
