/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rpc.h"

bool_t
xdr_coord (XDR *xdrs, coord *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->x))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->y))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_tupla (XDR *xdrs, tupla *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->key))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->value1, MAX_STR))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->N_value2))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->V_value2.V_value2_val, (u_int *) &objp->V_value2.V_value2_len, MAX_V2,
		sizeof (double), (xdrproc_t) xdr_double))
		 return FALSE;
	 if (!xdr_coord (xdrs, &objp->value3))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_get_resp (XDR *xdrs, get_resp *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	 if (!xdr_tupla (xdrs, &objp->data))
		 return FALSE;
	return TRUE;
}
